export const pageIds = {
  home: 'Home',
  storeMain: 'InStoreMain',
  phonograph: 'Phonograph',
  phonographMV: 'PhonographMV',
  mailBox: 'MailBox_i',
  main: 'StoreMain',
  F11: 'F11',
  F12: 'F12',
  F13: 'F13',
  F14: 'F14',
  F15: 'F15',
  F16: 'F16',
  F17: 'F17',
  F18: 'F18',
  M1: 'M1',
  M2: 'M2',
  minisMachine: 'MinisMachine',
  U1: 'U1',
  U2: 'U2',
  daily: 'Daily',
  dailyDetail: 'DailyDetail',
  Tasks: 'Tasks'
};
