export default [
  {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image03.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image03.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image02.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image05.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image05.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image04.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image07.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image07.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image06.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image09.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image09.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image08.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image11.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image11.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image10.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image13.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image13.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image12.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image15.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image15.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image14.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image17.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image17.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image16.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image19.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image19.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image18.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image21.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image21.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image20.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image23.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image23.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image22.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image25.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image25.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image24.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image27.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image27.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image26.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image29.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image29.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image28.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image31.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image31.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image30.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image33.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image33.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image32.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image35.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image35.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image34.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image37.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image37.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image36.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image39.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image39.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image38.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image41.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image41.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image40.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image43.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image43.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image42.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image45.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image45.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image44.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image47.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image47.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image46.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image49.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image49.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image48.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image51.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image51.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image50.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image53.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image53.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image52.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image55.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image55.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image54.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image57.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image57.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image56.webp"),
        unlocked: true,
        key: []
      }, {
        id: 0,
        small: require("../../img/returnedMailCards/returnedMailCard_small/Image59.webp"),
        big: require("../../img/returnedMailCards/returnedMailCard/Image59.webp"),
        back: require("../../img/returnedMailCards/returnedMailCard/Image58.webp"),
        unlocked: true,
        key: []
      }
];
